name: deploy-mkdocs

# Only run this when the main branch mkdocs directory changes
on:
  push:
    branches:
    - main
    paths:
    - mkdocs/**

# This job installs dependencies, build the site, and pushes it to `gh-pages`
jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r mkdocs/requirements.txt
    # Build the site
    - name: Build the site
      run: |
        cd mkdocs
        mkdocs build -d ../docs/mkdocs
    # Push the changes to GitHub
    - name: Push changes to GitHub
      run: |
        git config user.name github-actions
        git config user.email triznam@si.edu
        git add .
        git commit -m "updated mkdocs page"
        git push